services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak-workshop-keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: "dev-file"
    command: ["start-dev", "--import-realm"]
    volumes:
      - "./:/export"
      - "./:/opt/keycloak/data/import"
